version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      target: dev
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/postgres
      TEST_DATABASE_URL: postgres://postgres:password@test-database:5432/postgres

    ports:
      - 4000:4000
    volumes:
      - ./back-end/src:/app/src
      - /app/node_modules
    depends_on:
      - database
  web-app:
    build:
      context: ./web-app
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./web-app/src:/app/src
      - /app/node_modules
    depends_on:
      - back-end

  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_PASS:-password123}
    expose:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database-content:/var/lib/postgresql/data
    expose:
      - 5432

  test-database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  database-content:
  redis-data:
  redis-conf:
