name: deploy-dev-on-staging

on: push

jobs:
  deploy-dev-on-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to deploy dev branch on staging environment server
        run: echo 'Hello from github'
