name: build-test-deploy-staging

on: push

jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and test back-end
        run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end

  web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and test web-app
        run: docker compose -f docker-compose.ci.web-app.yml up --build --exit-code-from web-app

  deploy-main-on-staging:
    needs: [back-end, web-app]
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to deploy main branch on staging environment
        run: curl ${{ secrets.URL_WEBHOOK_DEPLOY_DEV_ON_STAGING }}
